name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission fo gradlew
      run: chmod +x gradlew
    - name: Run tests with gradle
      run: ./gradlew test
    - name: Code coverage report
      run: ./gradlew jacocoTestReport
    - name: Data to Codecov
      run: bash<(curl -s https://codecov.io/bash)
